### ISSUE TITLE
web server availability is not enabled by default via Rails 4.2

### ISSUE THREAD

**Issue by st-atila** [nilbus/pinewood-derby#61]
>3.3 Default Host for rails server
Due to a change in Rack, rails server now listens on localhost instead of 0.0.0.0 by default. ..
However, with this change you will no longer be able to access the Rails server from a different machine... In such cases, please start the server with 'rails server -b 0.0.0.0' to restore the old behavior.
> from-  http://edgeguides.rubyonrails.org/4_2_release_notes.html .

I have successfully edited the **Procfile** like:
```web: bundle exec rails server -b 0.0.0.0 -p 80 -e ${RAILS_ENV:-production````

Thank You, for making this project!

**Comment by nilbus** [comment]
Good catch! Would you be interested in doing a pull request to share that
change? Otherwise I can do it.

Edward

**Comment by st-atila** [comment]
Thank you, however, I would rather, at this time, if you would be so kind as to do it; this would be my first pull request (I am only just now reading about it, and I don't believe I have enough time to digest the concepts). Thanks.
